[misc]
seed = 42

[correction]
min_segment_proportion_agreement = 0.66

[transforms.annots]
time_precision = 0.001
min_label_duration = 0.02
lonely_labels = [ "cri", "TRASH",]
min_silence_gap = 0.001
silence_tag = "SIL"
merge_consecutive_labels = false

[transforms.audio]
audio_features = [ "mfcc", "delta", "delta2",]
sampling_rate = 300000
n_mfcc = 13
hop_length = 0.002
win_length = 0.004
n_fft = 2048
fmin = 30000
fmax = 110000
lifter = 40

[transforms.training]
max_sequences = -1
test_ratio = 0.2
iterative_fit = false

[model.syn]
units = 1000
sr = "0.16909416028190524"
leak = "0.22474737466287856"
iss = "0.010763023963055198"
isd = "1.1751733206453638"
isd2 = "0.0006836984566407328"
ridge = "4.468839759263115e-05"
backend = "multiprocessing"
workers = -1
seed = 3342

[model.nsyn]
units = 1000
sr = 0.4
leak = 0.1
iss = 0.0005
isd = 0.02
isd2 = 0.002
ridge = 1e-8
backend = "multiprocessing"
workers = -1

[transforms.audio.delta]
padding = "wrap"

[transforms.audio.delta2]
padding = "wrap"

[transforms.training.balance]
min_silence_duration = 0.2

[transforms.training.balance.data_augmentation]
noise_std = 0.01
